### PR TITLE
Only support otx log sematics

### LINKED ISSUE #101: Too many SD logs causes cpulimit error
### Describe the bug
RM TX16s - One day when using specific model on radio, started getting error of cpulimit
Changing to other models works fine

Appears a large number of logs associated with model cause this error

### To reproduce
1. Set up any model
2. In my case I have SD card logging enabled via Special Function when arm condition met
3. Accumulate numerous logs (actual per model limitation not known, only that flushing log folder rectifies issue)
4. Next startup receive error, presumably one of the startup functions is to parse log files and crashes when too many for the model are in there
4a. Able to work around as well by changing model name thus breaking link to SD card logs

### Expected behavior
Clearly this is some technical limitation or similar, expectation is to have unlimited logging, however, I suppose some reasonable accommodation such as only look at last X number of logs to rectify problem.

### Screenshots
N/A

### PR DESCRIPTION
**Pull request by stronnag**
Regrettably, the EdgeTX changes to log name semantics have proved to be an ongoing problem for the INAV Lua widget's log replay capability; in particular:

* The need to use the `dir()` function to enumerate log files leaves the script open to "CPU limit" forced termination when the user has numerous log files.  
* The need to use `table.sort()` to prune the list of log files meant that log replay was not available on small screen / B&W radios.

  The replay function has therefore been changed to only support OpenTX file names. Logs may still be replayed on EdgeTX by renaming the required file (`MODEL-YYYY-MM-DD_HHMMSS.csv` to `MODEL-YYYY-MM-DD.csv` (i.e. without the time part).

Fixes #101 (again).

### CODE REVIEW

**Comment by rickgode** [comment]
I know many might not find this worthwhile, but I really like it and am glad the functionality can work if we rename the file.  I renamed the file and took out the time, but my playback log is still greyed out.  Am I missing something?  I just updated to EdgeTX 2.10.  

Thank you

**Comment by stronnag** [comment]
Works OK here in ETX 2.10. Note that:
* The log finder only looks back 15 days in order to conserve resources.
* The log must start with the current model's name.

```
$ ls LOGS/
'Mr Spaced Out-2023-08-15-165737.csv'  'Mr Spaced Out-2024-05-12.csv'
```

So for "Mr Spaced Out", there is one valid log on 2024-05-12 (and until 2024-05-27).

image

**Comment by stronnag** [comment]
And the LOGS directory is read once, at startup.

**Comment by rickgode** [comment]
Thank you!  It was the 15 days.  I thought it was only the naming convention.

**Comment by rickgode** [comment]
One last question.  Now that I have the inav playback working.  What step am I missing to run this in companion.  Specifically, I was wanting to screen record the inav telemetry script running the log in companion so I could overlay it on my flight footage.  When I simulate my radio in companion and scroll over to my inav screen, there is nothing there.

Thanks Again.

**Comment by stronnag** [comment]
> One last question. Now that I have the inav playback working. What step am I missing to run this in companion. Specifically, I was wanting to screen record the inav telemetry script running the log in companion so I could overlay it on my flight footage. When I simulate my radio in companion and scroll over to my inav screen, there is nothing there.
> 
> Thanks Again.

No idea, the image I posted was from companion, and  here companion plays the log file correctly (& thusly, a few moments on from the first image):
image

**Comment by rickgode** [comment]
Thank you again.  It helps to read...  I needed the LuaTelemetry v2.2.4_lua.zip : Source LUA, compiles on the device, may be required in the simulator.  I was using my SD card of my transmitter.

Thanks!

**Pull request merged**
