### PR TITLE
revert old CRSF tests (#113)

### PR DESCRIPTION
**Pull request by stronnag**
Combines old CRSF test with newer test from #78 (which broke CRSF/OpenTX)

### CODE REVIEW

**Comment by stronnag** [comment]
@rmaia3d could you please test that current master still behaves correctly for your diversity RX ?

**Comment by rmaia3d** [comment]
Ok, I will test it as soon as possible and report the results!

**Comment by rmaia3d** [comment]
Sorry for the delay, but finally had some time to test. The telemetry detection works just fine with my diversity Rx's using the lua in master branch.

However, the RFMD detection seems broken. It doesn't detect the packet rate, showing only "50Hz", regardless of what's actually being used.

I did some investigation and it looks like the `data.elrs` parameter is not being updated accordingly (it is not detecting the ELRS major version). It's value remains as either 0 or -1. I couldn't find the reason for that, as I couldn't locate where the initial ELRS detection calls are made, but I suspect something is broken there.

Previous version of the scripts I was running (from late Feb/2023) was running just fine (and still is). So, some change in master since then probably broke this.

**Comment by stronnag** [comment]
Thanks. I now have an ELRS RX, so I can check this.

**Comment by stronnag** [comment]
2.2.2 is working OK here. Displays the correct packet rate as set via the ELRS widget (ELRS 3)

**Comment by rmaia3d** [comment]
If it is working for you, it probably was a mess up on my part. I will try testing again as soon as possible.

**Pull request merged**
