### PR TITLE
workaround edge2.6 getFieldInfo breakage

### LINKED ISSUE #23: Edge 2.6rc2 breaks the inav telemetry widget
An Edge "enhancement" in 2.6-rc2 breaks backwards compatibility in `getFieldInfo` and hence the inav script.
trivial fix inbound ...

### PR DESCRIPTION
**Pull request by stronnag**
Fixes #23 
**Don't release yet**, in case they break more backwards compatibility prior to the 2.6 release

### CODE REVIEW

**Comment by stronnag** [comment]
inav widget version update to be done.

**Comment by stronnag** [comment]
As this was broken both in the simulator and on the radio, here's a Zip in case anyone has a desperate need to use this with Edge 2.6-RC2

[LuaTelemetry_v2.0.2_lua.zip](https://github.com/iNavFlight/OpenTX-Telemetry-Widget/files/7810126/LuaTelemetry_v2.0.2_lua.zip)

**Comment by pfeerick** [comment]
This will not be needed in 2.6.0 - the culprit was fixed [here](https://github.com/EdgeTX/edgetx/commit/38bceab95ee50c6f87ea6b6a9fda49334a27e4a3).

**Comment by stronnag** [comment]
Thanks, I'm aware of that and will remove the workaround when there is a published ETX RC / Final incorporating https://github.com/EdgeTX/edgetx/pull/1423.

**Pull request merged**
